---
title: "JoshsTutDoc"
format: html
---

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
```

```{r}

system("plink --version")

```

```{r}
head(fam <- fread('data/penncath.fam'))
```

```{r}

clinical <- fread('data/penncath.csv')
clinical

```

```{r}

bim <- fread('data/penncath.bim')
head(bim)

```
```{r}

library(bigsnpr)
library(bigstatsr)
```


```{r}
snp_readBed("data/penncath.bed")
```


```{r}

penncath <- snp_attach("data/penncath.rds")
str(penncath)
```


```{r}
penncath$map$chromosome |> table()

```


```{r}
class(penncath$genotypes)

?bigstatsr::big_counts

big_counts(penncath$genotypes, ind.row = 1:10, ind.col = 1:10)

snp_stats <- big_counts(penncath$genotypes)
dim(snp_stats)

boxplot(snp_stats[4,])
```


```{r}
summary(snp_stats[4,])
```


```{r}
sample_stats <- big_counts(penncath$genotypes, byrow = TRUE)
sample_stats[, 1:10]
boxplot(sample_stats[4,])
```


```{r}
summary(sample_stats[4,])
```


```{r}
allele_dat <- sweep(x = sample_stats[1:3,], 
                    MARGIN = 1,
                    STATS = c(0, 1, 0),
                    FUN = "*") |> colSums()

boxplot(allele_dat/ncol(snp_stats))
```


```{r}
hist(allele_dat/ncol(snp_stats),
     main = "Zygosity",
     xlab = "Proportion of samples which are heterozygous")
```


```{r}
hist(snp_stats[1,])
```


```{r}
summary(snp_stats[1,])
```


```{r}
path_to_qc_penncath <- snp_plinkQC(
  plink.path = "~/bin/plink", 
  prefix.in = "data/penncath",
  prefix.out = "data/qc_penncath", 
  maf = 0.01
)
```


```{r}

system("plink --bfile data/penncath --make-bed --out data/penncath_clean")

```


```{r}
path_to_qc_penncath_bed <- snp_plinkQC(
  plink.path = "plink.exe", 
  prefix.in = "data/penncath_clean", 
  prefix.out = "data/qc_penncath", 
  maf = 0.01, 
  geno = 0.1, 
  mind = 0.1, 
  hwe = 1e-10, 
  autosome.only = TRUE
)
```


```{r}
qc_file_path <- snp_readBed(bedfile = path_to_qc_penncath_bed)

qc <- snp_attach(qc_file_path)

dim(qc$genotypes)
```


```{r}
class(penncath$genotypes)
first_10_snps <- penncath$genotypes[,1:10]
class(first_10_snps); dim(first_10_snps)
head(first_10_snps)
```
```{r}
# Imputations Portion
```


```{r}
library(data.table)
library(dplyr)
library(bigsnpr)
library(ggplot2)

obj <- snp_attach("data/qc_penncath.rds")
dim(obj$fam)
dim(obj$map)
dim(obj$genotypes)
```


```{r}
snp_stats <- bigstatsr::big_counts(obj$genotypes)

colnames(snp_stats) <- obj$map$marker.ID
snp_stats[,1:5]

(any_missing <- sum(snp_stats[4,] != 0))

call_rates <- colSums(snp_stats[1:3,])/colSums(snp_stats) 
head(call_rates)
```


```{r}
obj$geno_imputed <- snp_fastImputeSimple(Gna = obj$genotypes,
                                          method = "mode",
                                          ncores = nb_cores())


obj$geno_imputed$code256 <- bigsnpr::CODE_IMPUTE_PRED

imp_snp_stats <- big_counts(X.code = obj$geno_imputed)
imp_snp_stats[,1:5] 
```


```{r}
obj <- bigsnpr::snp_save(obj)
```


```{r}
obj <- snp_attach("data/qc_penncath.rds")
```


```{r}
svd_X <- big_SVD(obj$geno_imputed, 
                 big_scale(), 
                 k = 10 
                 )

saveRDS(svd_X, "data/svd_X.rds")

```


```{r}
svd_X <- readRDS("data/svd_X.rds")
str(svd_X)
plot(svd_X)
plot(svd_X, type = "scores")
```





```{r}
clinical <- fread('data/penncath.csv') |>
  mutate(across(.cols = c(sex, CAD),
                .fns = as.factor))
dplyr::glimpse(clinical)

plot(svd_X, type = "scores") +
  aes(color = clinical$sex) +
  labs(color = "Sex")
```


```{r}
K <- big_tcrossprodSelf(X = obj$geno_imputed,
                        fun.scaling = big_scale())

saveRDS(K, 'data/K.rds')
```


```{r}
#install.packages("corrplot")
K <- readRDS("data/K.rds")
library(corrplot)
corrplot::corrplot(K[1:50, 1:50]*(1/ncol(obj$geno_imputed)),
                   is.corr = FALSE,
                   tl.pos = "n")
```


```{r}
# Analysis Portion
```


```{r}
# creating the same obj
obj <- snp_attach("data/qc_penncath.rds")
```


```{r}
clinical <- fread("data/penncath.csv")
obj$fam <- dplyr::full_join(x = obj$fam,
                            y = clinical,
                            by = c('family.ID' = 'FamID'))
```


```{r}
svd_X <- readRDS(file = "data/svd_X.rds")

                          
pc <- sweep(svd_X$u, 2, svd_X$d, "*")
dim(pc) 
names(pc) <- paste0("PC", 1:ncol(pc))
```


```{r}
obj.gwas <- big_univLogReg(X = obj$geno_imputed,
                           y01.train = obj$fam$CAD,
                           covar.train = pc[,1:5],
                           ncores = nb_cores())

saveRDS(object = obj.gwas, file = "data/gwas.rds")
```


```{r}
obj.gwas <- readRDS("data/gwas.rds")
```


```{r}
qq <- bigsnpr::snp_qq(obj.gwas)
(qq)
```

```{r}
viridis22 <- c(rep(c("#fde725", "#90d743", "#35b779", "#21918c", "#31688e", 
                "#443983", "#440154"), 3), "#fde725")

manh <- snp_manhattan(gwas = obj.gwas,
              infos.chr = obj$map$chromosome,
              infos.pos = obj$map$physical.pos,
              colors = viridis22)

(manh)

```

```{r}
signif_threshold <- 5e-8 
suggest_threshold <- 5e-6 

(manh + 
  geom_hline(yintercept = -log10(signif_threshold),
             # note: plot y-axis is on -log10 scale 
             color = "#35b779",
             lty = 2) + 
  geom_hline(yintercept = -log10(suggest_threshold),
             color = "#443983",
             lty = 2)
)
```




